[package]
name = "dustroute-cli"
description = "Command-line interface for DustRoute"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
dustroute-app = { path = "../dustroute-app" }
dustroute-translate = { path = "../dustroute-translate" }
serde_json = "1.0"

[lints]
workspace = true
