//! Immutable Rust definitions; world adapters supply facts and apply effects.
use crate::law::{
    definition::{Definition, Handler},
    static_program::{Expression::*, Step::*},
};

pub const BLOCK_TRAITS_V1: Definition = Definition::new(
    &[("kind", 15), ("form", 7)],
    &[
        ("shape", 0, 4),
        ("dust_support", 0, 1),
        ("weak", 0, 1),
        ("strong", 0, 1),
        ("dust_drive", 0, 1),
        ("rise_shape", 0, 2),
        ("blocks_rise", 0, 1),
        ("kind_support", 0, 1),
        ("kind_weak", 0, 1),
        ("kind_strong", 0, 1),
        ("repeater_reads", 0, 1),
        ("kind_dust_drive", 0, 1),
        ("needs_support", 0, 1),
        ("support_below", 0, 1),
        ("wire_connect_mode", 0, 3),
        ("strong_targets", 0, 5),
        ("direct_mode", 0, 3),
        ("relay_receiver", 0, 1),
    ],
    &[],
    &[Handler {
        name: "evaluate",
        body: &[
            If(
                Equal(&Input("kind"), &Constant(0)),
                &[
                    Set("shape", Constant(0)),
                    Set("dust_support", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(0)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(0)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(0)),
                    Set("strong_targets", Constant(0)),
                    Set("direct_mode", Constant(0)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(1)),
                &[
                    Set("shape", Constant(1)),
                    Set("dust_support", Constant(1)),
                    Set("weak", Constant(1)),
                    Set("strong", Constant(1)),
                    Set("dust_drive", Constant(1)),
                    Set("rise_shape", Constant(2)),
                    Set("blocks_rise", Constant(1)),
                    Set("kind_support", Constant(1)),
                    Set("kind_weak", Constant(1)),
                    Set("kind_strong", Constant(1)),
                    Set("repeater_reads", Constant(1)),
                    Set("kind_dust_drive", Constant(1)),
                    Set("needs_support", Constant(0)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(0)),
                    Set("strong_targets", Constant(0)),
                    Set("direct_mode", Constant(0)),
                    Set("relay_receiver", Constant(0)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(2)),
                &[
                    Set("shape", Constant(1)),
                    Set("dust_support", Constant(1)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(2)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(1)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(0)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(0)),
                    Set("strong_targets", Constant(0)),
                    Set("direct_mode", Constant(0)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(3)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(0)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(1)),
                    Set("support_below", Constant(1)),
                    Set("wire_connect_mode", Constant(1)),
                    Set("strong_targets", Constant(0)),
                    Set("direct_mode", Constant(0)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(4)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(0)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(1)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(1)),
                    Set("strong_targets", Constant(4)),
                    Set("direct_mode", Constant(1)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(5)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(0)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(1)),
                    Set("support_below", Constant(1)),
                    Set("wire_connect_mode", Constant(2)),
                    Set("strong_targets", Constant(2)),
                    Set("direct_mode", Constant(2)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(6)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(0)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(1)),
                    Set("support_below", Constant(1)),
                    Set("wire_connect_mode", Constant(2)),
                    Set("strong_targets", Constant(2)),
                    Set("direct_mode", Constant(2)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(7)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(0)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(1)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(1)),
                    Set("strong_targets", Constant(1)),
                    Set("direct_mode", Constant(1)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(8)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(0)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(1)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(1)),
                    Set("strong_targets", Constant(1)),
                    Set("direct_mode", Constant(1)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(9)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(0)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(1)),
                    Set("support_below", Constant(1)),
                    Set("wire_connect_mode", Constant(1)),
                    Set("strong_targets", Constant(1)),
                    Set("direct_mode", Constant(1)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(10)),
                &[
                    Set("shape", Constant(1)),
                    Set("dust_support", Constant(1)),
                    Set("weak", Constant(1)),
                    Set("strong", Constant(1)),
                    Set("dust_drive", Constant(1)),
                    Set("rise_shape", Constant(2)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(1)),
                    Set("kind_weak", Constant(1)),
                    Set("kind_strong", Constant(1)),
                    Set("repeater_reads", Constant(1)),
                    Set("kind_dust_drive", Constant(1)),
                    Set("needs_support", Constant(0)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(0)),
                    Set("strong_targets", Constant(0)),
                    Set("direct_mode", Constant(0)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(11)),
                &[
                    Set("shape", Constant(1)),
                    Set("dust_support", Constant(1)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(2)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(1)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(0)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(1)),
                    Set("strong_targets", Constant(5)),
                    Set("direct_mode", Constant(1)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(12)),
                &[
                    Set("shape", Constant(1)),
                    Set("dust_support", Constant(1)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(2)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(1)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(0)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(3)),
                    Set("strong_targets", Constant(3)),
                    Set("direct_mode", Constant(3)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(13)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(1)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(2)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(1)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(0)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(0)),
                    Set("strong_targets", Constant(0)),
                    Set("direct_mode", Constant(0)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(14)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(1)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(2)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(1)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(0)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(0)),
                    Set("strong_targets", Constant(0)),
                    Set("direct_mode", Constant(0)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("kind"), &Constant(15)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(1)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("rise_shape", Constant(2)),
                    Set("blocks_rise", Constant(0)),
                    Set("kind_support", Constant(1)),
                    Set("kind_weak", Constant(0)),
                    Set("kind_strong", Constant(0)),
                    Set("repeater_reads", Constant(0)),
                    Set("kind_dust_drive", Constant(0)),
                    Set("needs_support", Constant(0)),
                    Set("support_below", Constant(0)),
                    Set("wire_connect_mode", Constant(0)),
                    Set("strong_targets", Constant(0)),
                    Set("direct_mode", Constant(0)),
                    Set("relay_receiver", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("form"), &Constant(2)),
                &[
                    Set("shape", Constant(3)),
                    Set("dust_support", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                ],
                &[],
            ),
            If(
                Equal(&Input("form"), &Constant(3)),
                &[
                    Set("shape", Constant(2)),
                    Set("dust_support", Constant(1)),
                    Set("rise_shape", Constant(1)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                ],
                &[],
            ),
            If(
                Equal(&Input("form"), &Constant(4)),
                &[
                    Set("shape", Constant(1)),
                    Set("dust_support", Constant(1)),
                    Set("rise_shape", Constant(2)),
                    Set("weak", Constant(1)),
                    Set("strong", Constant(1)),
                    Set("dust_drive", Constant(1)),
                    Set("blocks_rise", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("form"), &Constant(5)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                ],
                &[],
            ),
            If(
                Equal(&Input("form"), &Constant(6)),
                &[
                    Set("shape", Constant(4)),
                    Set("dust_support", Constant(1)),
                    Set("rise_shape", Constant(1)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                ],
                &[],
            ),
            If(
                Equal(&Input("form"), &Constant(7)),
                &[
                    Set("shape", Constant(1)),
                    Set("dust_support", Constant(1)),
                    Set("rise_shape", Constant(2)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("blocks_rise", Constant(0)),
                ],
                &[],
            ),
            If(
                Maximum(
                    &Equal(&Input("kind"), &Constant(14)),
                    &Equal(&Input("kind"), &Constant(15)),
                ),
                &[
                    Set("dust_support", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("blocks_rise", Constant(1)),
                ],
                &[],
            ),
            If(
                Equal(&Input("form"), &Constant(1)),
                &[
                    Set("shape", Constant(1)),
                    Set("dust_support", Constant(0)),
                    Set("rise_shape", Constant(0)),
                    Set("weak", Constant(0)),
                    Set("strong", Constant(0)),
                    Set("dust_drive", Constant(0)),
                    Set("blocks_rise", Constant(1)),
                ],
                &[],
            ),
        ],
    }],
);

pub const WIRE_SHAPE_V1: Definition = Definition::new(
    &[
        ("side_connects", 1),
        ("support_shape", 2),
        ("upper_wire", 1),
        ("blocked", 1),
        ("side_air", 1),
        ("lower_wire", 1),
    ],
    &[("shape", 0, 2)],
    &[],
    &[Handler {
        name: "evaluate",
        body: &[If(
            Input("side_connects"),
            &[Set("shape", Constant(1))],
            &[If(
                And(
                    &Not(&Equal(&Input("support_shape"), &Constant(0))),
                    &And(&Input("upper_wire"), &Not(&Input("blocked"))),
                ),
                &[Set("shape", Input("support_shape"))],
                &[If(
                    And(&Input("side_air"), &Input("lower_wire")),
                    &[Set("shape", Constant(1))],
                    &[],
                )],
            )],
        )],
    }],
);

pub const WIRE_TRANSFER_V1: Definition = Definition::new(
    &[
        ("elevation", 2),
        ("source_arm", 2),
        ("sink_arm", 2),
        ("support_shape", 2),
        ("conducts", 1),
        ("clear", 1),
        ("enforce_clearance", 1),
    ],
    &[("connected", 0, 1)],
    &[],
    &[Handler {
        name: "evaluate",
        body: &[
            If(
                Equal(&Input("elevation"), &Constant(0)),
                &[Set(
                    "connected",
                    And(
                        &Not(&Equal(&Input("source_arm"), &Constant(0))),
                        &Not(&Equal(&Input("sink_arm"), &Constant(0))),
                    ),
                )],
                &[],
            ),
            If(
                Equal(&Input("elevation"), &Constant(1)),
                &[Set(
                    "connected",
                    And(
                        &And(
                            &Not(&Equal(&Input("support_shape"), &Constant(0))),
                            &Equal(&Input("source_arm"), &Input("support_shape")),
                        ),
                        &Maximum(&Not(&Input("enforce_clearance")), &Input("clear")),
                    ),
                )],
                &[],
            ),
            If(
                Equal(&Input("elevation"), &Constant(2)),
                &[Set(
                    "connected",
                    And(
                        &And(
                            &Not(&Equal(&Input("support_shape"), &Constant(0))),
                            &Equal(&Input("sink_arm"), &Input("support_shape")),
                        ),
                        &Input("conducts"),
                    ),
                )],
                &[],
            ),
        ],
    }],
);

pub const WIRE_WEAK_POWER_V1: Definition = Definition::new(
    &[("relation", 2), ("arm", 2)],
    &[("connected", 0, 1)],
    &[],
    &[Handler {
        name: "evaluate",
        body: &[Set(
            "connected",
            Maximum(
                &Equal(&Input("relation"), &Constant(0)),
                &And(
                    &Equal(&Input("relation"), &Constant(1)),
                    &Not(&Equal(&Input("arm"), &Constant(0))),
                ),
            ),
        )],
    }],
);
