[package]
name = "dustroute-library"
description = "Provenance-aware logical and physical component catalog for DustRoute"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
schemars = "1.2"
dustroute-ir = { path = "../dustroute-ir" }
dustroute-minecraft = { path = "../dustroute-minecraft" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
dustroute-codec = { path = "../dustroute-codec" }
serde_json = "1.0"
