[package]
name = "dustroute-optimize"
description = "Placement and semantic optimization for DustRoute"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
dustroute-physical = { path = "../dustroute-physical" }
dustroute-translate = { path = "../dustroute-translate" }

[lints]
workspace = true
