use dustroute_minecraft::law::LawProgram;

#[test]
fn all_rust_definitions_preserve_the_complete_frozen_programs() {
    let definitions = [
        (
            dustroute_minecraft::law::builtins::spatial::BLOCK_TRAITS_V1,
            include_str!("fixtures/typed-laws-v1/block-traits-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::spatial::WIRE_SHAPE_V1,
            include_str!("fixtures/typed-laws-v1/wire-shape-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::spatial::WIRE_TRANSFER_V1,
            include_str!("fixtures/typed-laws-v1/wire-transfer-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::spatial::WIRE_WEAK_POWER_V1,
            include_str!("fixtures/typed-laws-v1/wire-weak-power-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::repeater_law::REPEATER_COMPATIBILITY_V1,
            include_str!("fixtures/typed-laws-v1/repeater-compatibility-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::repeater_law::REPEATER_BOUNDED_V1,
            include_str!("fixtures/typed-laws-v1/repeater-bounded-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::lamp_law::LAMP_COMPATIBILITY_V1,
            include_str!("fixtures/typed-laws-v1/lamp-compatibility-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::lamp_law::LAMP_BOUNDED_V1,
            include_str!("fixtures/typed-laws-v1/lamp-bounded-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::comparator_law::COMPARATOR_COMPATIBILITY_V1,
            include_str!("fixtures/typed-laws-v1/comparator-compatibility-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::observer_law::OBSERVER_COMPATIBILITY_V1,
            include_str!("fixtures/typed-laws-v1/observer-compatibility-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_law::PISTON_STATE_V1,
            include_str!("fixtures/typed-laws-v1/piston-state-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_law::PISTON_MOTION_V1,
            include_str!("fixtures/typed-laws-v1/piston-motion-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_law::PISTON_CONNECTION_V1,
            include_str!("fixtures/typed-laws-v1/piston-connection-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_law::PISTON_PAYLOAD_V1,
            include_str!("fixtures/typed-laws-v1/piston-payload-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_law::PISTON_ELECTRICAL_PAYLOAD_JAVA_1_21_11_V3,
            include_str!("fixtures/typed-laws-v1/piston-electrical-payload-java-1-21-11-v3.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_motion_law::PISTON_CONTROL_JAVA_1_21_11_V1,
            include_str!("fixtures/typed-laws-v1/piston-control-java-1-21-11-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_motion_law::PISTON_CARRIER_JAVA_1_21_11_V1,
            include_str!("fixtures/typed-laws-v1/piston-carrier-java-1-21-11-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_motion_law::PISTON_GEOMETRY_JAVA_1_21_11_V2,
            include_str!("fixtures/typed-laws-v1/piston-geometry-java-1-21-11-v2.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_motion_law::PISTON_HEAD_JAVA_1_21_11_V1,
            include_str!("fixtures/typed-laws-v1/piston-head-java-1-21-11-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_electrical_law::PISTON_SIGNAL_EMISSION_JAVA_1_21_11_V1,
            include_str!("fixtures/typed-laws-v1/piston-signal-emission-java-1-21-11-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_electrical_law::PISTON_CONDUCTOR_JAVA_1_21_11_V1,
            include_str!("fixtures/typed-laws-v1/piston-conductor-java-1-21-11-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_electrical_law::PISTON_POWER_QUERY_JAVA_1_21_11_V1,
            include_str!("fixtures/typed-laws-v1/piston-power-query-java-1-21-11-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::piston_electrical_law::REPEATER_CALLBACK_JAVA_1_21_11_V1,
            include_str!("fixtures/typed-laws-v1/repeater-callback-java-1-21-11-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::dust::DUST,
            include_str!("fixtures/typed-laws-v1/dust-law-v1.json"),
        ),
        (
            dustroute_minecraft::law::builtins::torch::TORCH,
            include_str!("fixtures/typed-laws-v1/torch-law-v1.json"),
        ),
    ];
    for (definition, frozen) in definitions {
        let old: LawProgram = serde_json::from_str(frozen).unwrap();
        let program = definition.program();
        assert_eq!(program, old);
        program.compile().unwrap();
    }
}
